# Generated by Django 4.0.1 on 2022-02-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_magazine_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='real_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
