# Generated by Django 4.0.1 on 2022-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_magazine_real_content_alter_magazine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
