# Generated by Django 4.0.1 on 2022-02-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0007_static_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('real_content', models.TextField(default='')),
                ('image', models.CharField(max_length=50)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
