# Generated by Django 4.0.1 on 2022-02-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0008_magazine_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Magazine_News',
            new_name='MagazineNews',
        ),
    ]
